spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false

youtube:
  video_url: https://www.googleapis.com/youtube/v3/videos
  video_category_url: https://www.googleapis.com/youtube/v3/videoCategories
  key: ${YOUTUBE_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
