spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

youtube:
  video_url: https://www.googleapis.com/youtube/v3/videos
  video_category_url: https://www.googleapis.com/youtube/v3/videoCategories
  key: ${YOUTUBE_API_KEY}

